services:
  # ✅ Keycloak (User Management)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev"]
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - cebratechai-network
    depends_on:
      kong:
        condition: service_healthy  # ✅ รอ Kong พร้อมก่อนใช้งาน

  # ✅ Kong Database Migrations
  kong-migrations:
    image: kong/kong-gateway:latest
    container_name: kong-migrations
    restart: "no"  # ✅ ให้รันแค่ครั้งเดียว
    command: "kong migrations bootstrap"
    env_file: .env
    networks:
      - cebratechai-network

  # ✅ Kong API Gateway
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    restart: always
    env_file: .env
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_DECLARATIVE_CONFIG: ${KONG_DECLARATIVE_CONFIG}
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - kong_data:/usr/local/kong
      - ./kong.yaml:/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    networks:
      - cebratechai-network
    depends_on:
      kong-migrations:
        condition: service_completed_successfully  # ✅ รอ Migrations ให้เสร็จแล้วค่อยเริ่ม Kong

  # ✅ Konga (GUI for Kong)
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    networks:
      - cebratechai-network
    depends_on:
      kong:
        condition: service_healthy  # ✅ รอ Kong พร้อมก่อนใช้งาน

networks:
  cebratechai-network:

volumes:
  kong_data:
